import { Experience } from '../app/core/experience/experience';

export const MOCK_EXPERIENCES: Experience[] = [
    {
        id: 1,
        status: 1,
        host: {
            is_valid: 1,
            is_host: 1,
            is_helper: 0,
            premium_until: null,
            firstname: 'David',
            lastname: 'Cohen',
            email: 'david.cohen@gmail.com',
            phone: null,
            old: 34,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
            city: 'Bordeaux',
            country: 'France',
            profile_picture_url: null,
            last_login: null,
            response_rate: null,
            response_time:  null,
        },
        property: {
            type: 'Hostel',
            name: 'The Great Backpacker',
            address: null,
            zipcode: null,
            city: 'Lomond',
            country: 'United Kingdom',
        },
        title: 'Join our amazing team in the heart of Scotland',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        min_week: 2,
        max_week: 4,
        number_volunteers: 4,
        volunteer_hours: 3,
        days_off: 1,
        accomodation_type: 'Private room',
        has_breakfast: 1,
        has_lunch: 0,
        has_diner: 0,
        has_food_allowance: 0,
        has_free_activities: 0,
        url: 'join-our-amazing-team-in-the-heart-of-scotland',
        cover_picture_url: null,
        other_pictures_url: null,
    }
] 