import { Experience } from '../app/core/experience/experience';

export const MOCK_EXPERIENCE: Experience = {
    id: 1,
    status: 1,
    host: {
        is_valid: 1,
        is_host: 1,
        is_helper: 0,
        premium_until: null,
        firstname: 'David',
        lastname: 'Cohen',
        email: 'david.cohen@gmail.com',
        phone: null,
        old: 34,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        city: 'Bordeaux',
        country: 'France',
        profile_picture_url: null,
        last_login: null,
        response_rate: null,
        response_time:  null,
    },
    property: {
        type: 'Hostel',
        name: 'The Great Backpacker',
        address: '200 Avenue Legrand',
        zipcode: '33000',
        city: 'Lomond',
        country: 'United Kingdom',
    },
    title: 'Join our amazing team in the heart of Scotland',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum. Fusce vitae consectetur tellus, vitae posuere erat. In vel ante ornare, tristique magna quis, gravida libero. Praesent volutpat maximus justo, vitae convallis elit tempor a. Sed facilisis facilisis iaculis. Ut molestie ultricies tempor. Aenean fringilla laoreet congue. Sed molestie nulla sit amet risus tincidunt vehicula. In vestibulum augue ut vulputate gravida. Fusce pulvinar eleifend leo vel porta. Suspendisse at dapibus tellus. Ut sed justo vel diam ullamcorper ullamcorper at et ligula.',
    requirements: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
    min_weeks: 2,
    max_weeks: 4,
    number_volunteers: 4,
    volunteer_hours: 3,
    days_off: 1,
    accomodation_type: 'Private room',
    has_breakfast: 1,
    has_lunch: 1,
    has_diner: 1,
    has_food_allowance: 1,
    has_free_activities: 1,
    rating: 4,
    number_comments: 1,
    url: 'join-our-amazing-team-in-the-heart-of-scotland',
    cover_picture_url: 'http://lorempixel.com/1200/1200/nature',
    other_pictures_url: ['http://lorempixel.com/800/600/city', 'http://lorempixel.com/800/600/city', 'http://lorempixel.com/800/600/city'],
}

export const MOCK_EXPERIENCES: Experience[] = [
    {
        id: 1,
        status: 1,
        host: {
            is_valid: 1,
            is_host: 1,
            is_helper: 0,
            premium_until: null,
            firstname: 'David',
            lastname: 'Cohen',
            email: 'david.cohen@gmail.com',
            phone: null,
            old: 34,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
            city: 'Bordeaux',
            country: 'France',
            profile_picture_url: null,
            last_login: null,
            response_rate: null,
            response_time:  null,
        },
        property: {
            type: 'Hostel',
            name: 'The Great Backpacker',
            address: '200 Avenue Legrand',
            zipcode: '33000',
            city: 'Lomond',
            country: 'United Kingdom',
        },
        title: 'Join our amazing team in the heart of Scotland',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        requirements: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        min_weeks: 2,
        max_weeks: 4,
        number_volunteers: 4,
        volunteer_hours: 3,
        days_off: 1,
        accomodation_type: 'Private room',
        has_breakfast: 1,
        has_lunch: 1,
        has_diner: 1,
        has_food_allowance: 1,
        has_free_activities: 1,
        rating: 4,
        number_comments: 1,
        url: 'join-our-amazing-team-in-the-heart-of-scotland',
        cover_picture_url: 'http://lorempixel.com/800/600/city',
        other_pictures_url: null,
    },
    {
        id: 1,
        status: 1,
        host: {
            is_valid: 1,
            is_host: 1,
            is_helper: 0,
            premium_until: null,
            firstname: 'David',
            lastname: 'Cohen',
            email: 'david.cohen@gmail.com',
            phone: null,
            old: 34,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
            city: 'Bordeaux',
            country: 'France',
            profile_picture_url: null,
            last_login: null,
            response_rate: null,
            response_time:  null,
        },
        property: {
            type: 'Hostel',
            name: 'The Great Backpacker',
            address: '200 Avenue Legrand',
            zipcode: '33000',
            city: 'Lomond',
            country: 'United Kingdom',
        },
        title: 'Join our amazing team in the heart of Scotland',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        requirements: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        min_weeks: 2,
        max_weeks: 4,
        number_volunteers: 4,
        volunteer_hours: 3,
        days_off: 1,
        accomodation_type: 'Private room',
        has_breakfast: 1,
        has_lunch: 1,
        has_diner: 1,
        has_food_allowance: 1,
        has_free_activities: 1,
        rating: 4,
        number_comments: 2,
        url: 'join-our-amazing-team-in-the-heart-of-scotland',
        cover_picture_url: 'http://lorempixel.com/900/600/nature',
        other_pictures_url: null,
    },
    {
        id: 1,
        status: 1,
        host: {
            is_valid: 1,
            is_host: 1,
            is_helper: 0,
            premium_until: null,
            firstname: 'David',
            lastname: 'Cohen',
            email: 'david.cohen@gmail.com',
            phone: null,
            old: 34,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
            city: 'Bordeaux',
            country: 'France',
            profile_picture_url: null,
            last_login: null,
            response_rate: null,
            response_time:  null,
        },
        property: {
            type: 'Hostel',
            name: 'The Great Backpacker',
            address: '200 Avenue Legrand',
            zipcode: '33000',
            city: 'Lomond',
            country: 'United Kingdom',
        },
        title: 'Join our amazing team in the heart of Scotland',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        requirements: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        min_weeks: 2,
        max_weeks: 4,
        number_volunteers: 4,
        volunteer_hours: 3,
        days_off: 1,
        accomodation_type: 'Private room',
        has_breakfast: 1,
        has_lunch: 1,
        has_diner: 1,
        has_food_allowance: 1,
        has_free_activities: 1,
        rating: 4,
        number_comments: 1,
        url: 'join-our-amazing-team-in-the-heart-of-scotland',
        cover_picture_url: 'http://lorempixel.com/400/600/people',
        other_pictures_url: null,
    },
    {
        id: 1,
        status: 1,
        host: {
            is_valid: 1,
            is_host: 1,
            is_helper: 0,
            premium_until: null,
            firstname: 'David',
            lastname: 'Cohen',
            email: 'david.cohen@gmail.com',
            phone: null,
            old: 34,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
            city: 'Bordeaux',
            country: 'France',
            profile_picture_url: null,
            last_login: null,
            response_rate: null,
            response_time:  null,
        },
        property: {
            type: 'Hostel',
            name: 'The Great Backpacker',
            address: '200 Avenue Legrand',
            zipcode: '33000',
            city: 'Lomond',
            country: 'United Kingdom',
        },
        title: 'Join our amazing team in the heart of Scotland',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        requirements: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at lorem lacus. Mauris rhoncus blandit rutrum.',
        min_weeks: 2,
        max_weeks: 4,
        number_volunteers: 1,
        volunteer_hours: 1,
        days_off: 3,
        accomodation_type: 'Private room',
        has_breakfast: 1,
        has_lunch: 1,
        has_diner: 1,
        has_food_allowance: 1,
        has_free_activities: 1,
        rating: 4,
        number_comments: 1,
        url: 'join-our-amazing-team-in-the-heart-of-scotland',
        cover_picture_url: 'http://lorempixel.com/900/900/nature',
        other_pictures_url: null,
    }
] 